### ISSUE TITLE
whereOneOf method of QueryBuilder is not working fine

### ISSUE THREAD

**Issue by vuolter** [onpage-dev/onpage-php#5]
Hello there,
I'm trying to perform a query `OR` condition using method `whereOneOf` (or through a custom filter added with `addRawFilter`).

When I write:
```
query->whereOneOf(fn (QueryBuilder $q) => $q->where($first_field, $sample_value));
query->whereOneOf(fn (QueryBuilder $q) => $q->where($second_field, $sample_value));
query->get();
```
I expect to match a result if one of `$first_field` or `$second_field` is equal to `$sample_value`, but right now I get the result only if the first `where` matches the value.

Same using a custom filter:
```
query->where($first_field, $sample_value);
query->addRawFilter(['_or', [$second_field, '=', $sample_value]]);
query->get();
```

Am I wrong about how these methods should work?
Thank you.

**Comment by gufoe** [comment]
Hello and thanks for the report! This function is not documented and I will soon add examples.
So this is what you are building with your example:
`[ _and, [_or, filter1], [_or, filter2] ]`
But you actually want this:
`[_or, filter1, filter2, ...]`

The correct code for your example would be this:
```php
$query->whereOneOf(fn (QueryBuilder $q) => $q->where($first_field, $sample_value)->where($second_field, $sample_value));
```

Let me know if this fixes your issue!

**Comment by vuolter** [comment]
Heey @gufoe thanks for the help, I confirm it works as expected now.
In the end seems I had misunderstood how that method actually worked. XD
